---
title: "recruitment data as of `r format(Sys.Date(),'%d/%m/%Y')`"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: menu
    logo: "bronchStop.png"
    self_contained: TRUE
    theme:
      base_font:
        google: Prompt
---

<!-- TODO LIST -->
<!-- set up netlify -->
<!-- set up github -->

```{r setup, include=FALSE}
library(flexdashboard)
library(aws.s3)

#library(tidyverse)
#library(janitor)
library(gt)
library(dplyr)
library(ggplot2)
library(maps)
library(mapproj)
library(viridis)
library(ggridges)

# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()

SECRET_ID <- Sys.getenv("SECRET_ID")
SECRET_KEY <- Sys.getenv("SECRET_KEY")
SECRET_REGION<- Sys.getenv("SECRET_REGION")
SECRET_BUCKETNAME<-Sys.getenv("SECRET_BUCKETNAME")

s3load("bronchStop.Rdata", bucket = SECRET_BUCKETNAME)

```
Column {data-width=550 .tabset}
-----------------------------------------------------------------------
### Leaderboard

```{r}
recruitment_by_site_table|>
  slice_head(n=10)|>
  mutate(Rank=c(1:n()))|>
  select(Rank,siteName,VE_study,total)|>
  gt()|>
  cols_align(align = "center",columns = VE_study)|>
    cols_label(
    siteName = "Site Name",
    VE_study = "VE Study",
    total = "Total")|>
  tab_header(
    title = md("BronchStop recruitment by site"),
  )

```


### All Sites

```{r}
recruitment_by_site_table|>
  arrange(siteID)|>
  select(siteName,VE_study,total)|>
  gt()|>
  cols_align(align = "center",columns = VE_study)|>
    cols_label(
    siteName = "Site Name",
    VE_study = "VE Study",
    total = "Total")|>
  tab_header(
    title = md("BronchStop recruitment by site"),
  )

```

### Map of Sites
```{r}
#recruitment_map
recruitment_by_site_table|>
  ggplot() +
  geom_polygon(data = UK, aes(x=long, y = lat, group = group), fill="grey", alpha=0.3) +
  geom_point(  aes(x=long, y=lat, size=total, colour=total, alpha=total), shape = 20, stroke=FALSE) +
  scale_size_continuous( name="Recruitment", trans="log", range=c(4,12),    breaks=mybreaks, labels = mybreaks_labels, guide = "legend") +
  scale_alpha_continuous(name="Recruitment", trans="log", range=c(0.1, .9), breaks=mybreaks, labels = mybreaks_labels, guide = "legend") +
  scale_colour_viridis(  name="Recruitment", trans="log", option="magma",   breaks=mybreaks, labels = mybreaks_labels, guide = "legend") +
  theme_void() + ylim(50,59) + coord_map() + 
  guides( colour = guide_legend("Recruitment",reverse = TRUE),
          size = guide_legend("Recruitment",reverse = TRUE),
          alpha = guide_legend("Recruitment",reverse = TRUE)
  ) +
  #ggtitle("BronchStart Sites") +
  theme(
    legend.position.inside = c(0.5, 0.8),
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#f5f5f2", color = NA), 
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    plot.title = element_text(size= 16, hjust=0.1, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
  )

```

### About

BronchStop is an extension of [the BronchStart study](https://doi.org/10.1093/infdis/jiad551) which will  evaluate the effectiveness of RSV vaccination in the UK.

We are recruiting children under the age of 2 years admitted with respiratory problems during the winter of 24/25 and asking which baby's mothers were vaccinated against RSV.

Our protocol is available [here](https://doi.org/10.12688%2Fwellcomeopenres.16778.2).

### Outputs

1) Our early report of parent's views on the RSV vaccine [Maternal views on RSV vaccination during the first season of implementation in England and Scotland- The Lancet Infectious Diseases](https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(25)00060-X/fulltext)

2) This is the pre print of our first in the UK assessment of the effectiveness of the vaccine against admission with RSV bronchiolitis. [Bivalent prefusion F vaccination in pregnancy and respiratory syncytial virus hospitalisation in infants: results of a  multi-centre, test-negative study](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5184994) 

3) A Radio 4 episode about the Born in Bradford cohort study. [Born in Bradford - Gasping for breath](https://www.bbc.co.uk/sounds/play/m0025cxn) 

4) One of our study team,  Dr Simon Drysdale contributed to this Royal College of Paediatrics podcast discussing the maternal RSV vaccine [The Paeds Round - Protecting infants with the maternal vaccine for RSV](https://learning.rcpch.ac.uk/home/podcasts/the-paeds-round-from-rcpch-and-medisense/)

5) Recent World Health Organization position paper on RSV immunisation [citing the BronchStop study]. (https://www.who.int/publications/i/item/WER10022)

Column {data-width=450}
-----------------------------------------------------------------------

### Virus Detections

```{r fig.width = 7, fig.height = 4}

ridge_graph_data|>
  ggplot(aes(x=studyWeek, y=height, height=count, fill=virus)) +
  geom_ridgeline()+
  theme_ridges()+
  scale_x_continuous("", breaks=seq(0,27,4),labels=axis_labels)+
  #scale_x_continuous("epidemiological week", breaks=seq(2,53,2),labels=c(seq(17,51,2),seq(1,16,2)))+
  #theme(legend.position = "bottom")+
  #guides(fill = guide_legend(nrow = 1))+
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        aspect.ratio=0.5)+
  ylab(NULL)

```

### Cumulative Recruitment

```{r fig.width = 7, fig.height = 4}

recruitment_graph|>
  ggplot(aes(x=studyWeek)) +
  geom_line(aes(y = cumulative_all))+
  geom_line(aes(y = cumulative_ve), color="red", linetype="twodash")+
  scale_x_continuous("", breaks=seq(0,27,4),labels=axis_labels)+
  scale_y_continuous("Recruitment")

```
