on:
  workflow_dispatch:
  schedule:
    - cron:  '0 17 * * *'
  push:
    branches: main
    
jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          packages: |
            any::flexdashboard
            any::aws.s3
            any::gt
            any::dplyr
            any::ggplot2
            any::mapproj
            any::maps
            any::viridis
            any::ggridges
 
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Import data
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SECRET_BUCKETNAME: ${{ secrets.SECRET_BUCKETNAME }}
        run: Rscript -e 'rmarkdown::render(input = "BronchStop_no_secrets.rmd")'

      - name: Rename file 
        run: mv BronchStop_no_secrets.html ./docs/index.html
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add site
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
